# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: bitso 0.4.0 ruby lib

Gem::Specification.new do |s|
  s.name = "bitso"
  s.version = "0.4.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jeffrey Wilcke"]
  s.date = "2014-03-09"
  s.description = "Ruby API for use with bitso."
  s.email = "stygeo@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".rspec",
    ".ruby-gemset",
    ".ruby-version",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "bitso.gemspec",
    "lib/bitso.rb",
    "lib/bitso/collection.rb",
    "lib/bitso/helper.rb",
    "lib/bitso/model.rb",
    "lib/bitso/net.rb",
    "lib/bitso/orders.rb",
    "lib/bitso/ticker.rb",
    "lib/bitso/transactions.rb",
    "spec/bitso_spec.rb",
    "spec/collection_spec.rb",
    "spec/fixtures/vcr_cassettes/bitso/balance.yml",
    "spec/fixtures/vcr_cassettes/bitso/order_book.yml",
    "spec/fixtures/vcr_cassettes/bitso/orders/all.yml",
    "spec/fixtures/vcr_cassettes/bitso/orders/buy.yml",
    "spec/fixtures/vcr_cassettes/bitso/orders/sell/failure.yml",
    "spec/fixtures/vcr_cassettes/bitso/ticker.yml",
    "spec/fixtures/vcr_cassettes/bitso/transactions.yml",
    "spec/fixtures/vcr_cassettes/bitso/user_transactions/all.yml",
    "spec/orders_spec.rb",
    "spec/spec_helper.rb",
    "spec/support/bitso_setup.rb",
    "spec/support/vcr.rb",
    "spec/transactions_spec.rb"
  ]
  s.homepage = "http://github.com/kojnapp/bitso"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "2.1.11"
  s.summary = "Bitso Ruby API"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activemodel>, [">= 3.1"])
      s.add_runtime_dependency(%q<activesupport>, [">= 3.1"])
      s.add_runtime_dependency(%q<rest_client>, [">= 1.7.3"])
      s.add_runtime_dependency(%q<ruby-hmac>, ["= 0.4.0"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, ["~> 1.3.5"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.4"])
    else
      s.add_dependency(%q<activemodel>, [">= 3.1"])
      s.add_dependency(%q<activesupport>, [">= 3.1"])
      s.add_dependency(%q<rest_client>, [">= 1.7.3"])
      s.add_dependency(%q<ruby-hmac>, ["= 0.4.0"])
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, ["~> 1.3.5"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
    end
  else
    s.add_dependency(%q<activemodel>, [">= 3.1"])
    s.add_dependency(%q<activesupport>, [">= 3.1"])
    s.add_dependency(%q<rest_client>, [">= 1.7.3"])
    s.add_dependency(%q<ruby-hmac>, ["= 0.4.0"])
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, ["~> 1.3.5"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
  end
end

